services:
  web1:
    build: .
    container_name: web1
  web2:
    build: .
    container_name: web2
  web3:
    build: .
    container_name: web3
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - web1
      - web2
      - web3
    